let KEV=null,NVD=null,EPSS=null,RW=null,MYCERT=null;
let NVD_BY_ID=new Map(),EPSS_BY_ID=new Map();
let PAGE=1; const PAGE_SIZE=50;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=n=>Number(n||0).toLocaleString();
function fmtDateTime(v){if(!v)return'Not collected';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString();}
function ageDays(s){if(!s)return Infinity;return(Date.now()-new Date(`${s}T00:00:00Z`).getTime())/86400000;}
function relTime(v){if(!v)return'Unknown time';const t=new Date(v).getTime();if(!Number.isFinite(t))return'Unknown time';const m=Math.max(0,Math.floor((Date.now()-t)/60000));if(m<60)return`${m}m ago`;const h=Math.floor(m/60);if(h<48)return`${h}h ago`;return`${Math.floor(h/24)}d ago`;}
function priorityLabel(s){return s>=75?'CRITICAL':s>=55?'HIGH':s>=35?'MEDIUM':'LOW';}
function ctiPriority(v){const sev=String(v.nvd?.cvss?.severity||'UNKNOWN').toUpperCase();let s=({CRITICAL:30,HIGH:24,MEDIUM:15,LOW:8,UNKNOWN:5})[sev]??5;const p=Number(v.epss?.epss||0);s+=p>=.7?35:p>=.5?32:p>=.2?28:p>=.1?24:p>=.05?20:p>=.01?14:6;if(v.ransomware)s+=25;const a=ageDays(v.dateAdded);s+=a<=7?10:a<=30?6:a<=90?3:0;s=Math.min(100,s);return{score:s,label:priorityLabel(s)};}
function buildUnified(){return(KEV?.vulnerabilities||[]).map(v=>{const x={...v,nvd:NVD_BY_ID.get(v.id)||null,epss:EPSS_BY_ID.get(v.id)||null};x.priority=ctiPriority(x);return x;});}
function sourceReady(x){return x?.meta?.status==='ok';}
function setHealth(id,state){const el=$(id);if(!el)return;const cls=state===true||state==='ok'?'ok':state==='warn'?'warn':'';el.className=`health-dot ${cls}`;}
function renderHeader(){const states=[sourceReady(KEV),sourceReady(NVD),sourceReady(EPSS),sourceReady(RW),sourceReady(MYCERT)];const n=states.filter(Boolean).length;const myDegraded=sourceReady(MYCERT)&&MYCERT?.meta?.lastAttemptStatus==='failed';$('feedStatus').textContent=n===5&&!myDegraded?'5 SOURCES LIVE':myDegraded?`${n} SOURCES · 1 DEGRADED`:`${n} SOURCE${n===1?'':'S'} LIVE`;$('liveDot').className=`dot ${n===5&&!myDegraded?'':'amber-dot'}`;setHealth('cisaHealthDot',states[0]);setHealth('nvdHealthDot',states[1]);setHealth('epssHealthDot',states[2]);setHealth('rwHealthDot',states[3]);setHealth('mycertHealthDot',myDegraded?'warn':states[4]);$('cisaCollectedAt').textContent=fmtDateTime(KEV?.meta?.collectedAt);$('nvdCollectedAt').textContent=fmtDateTime(NVD?.meta?.collectedAt);$('epssCollectedAt').textContent=fmtDateTime(EPSS?.meta?.collectedAt);$('rwCollectedAt').textContent=fmtDateTime(RW?.meta?.collectedAt);$('mycertCollectedAt').textContent=sourceReady(MYCERT)?fmtDateTime(MYCERT?.meta?.collectedAt):'Not collected';}
function renderTopMetrics(){const unified=buildUnified();const criticalPriority=unified.filter(x=>x.priority.label==='CRITICAL').length;$('total').textContent=fmt(KEV?.stats?.total);$('ransomware').textContent=fmt(KEV?.stats?.ransomwareRelated);$('critical').textContent=fmt(NVD?.stats?.critical);$('high').textContent=fmt(NVD?.stats?.high);$('priorityCriticalTop').textContent=fmt(criticalPriority);$('epss50Top').textContent=fmt(EPSS?.stats?.epssGe50);$('rwTotalVictims').textContent=sourceReady(RW)?fmt(RW.stats.totalVictims):'—';$('rwActiveGroups').textContent=sourceReady(RW)?fmt(RW.stats.activeGroups):'—';$('rw24h').textContent=sourceReady(RW)?fmt(RW.stats.claims24h):'—';$('rwCountries').textContent=sourceReady(RW)?fmt(RW.stats.countriesRecent):'—';const epssHigh=Number(EPSS?.stats?.epssGe50||0);const rw24=Number(RW?.stats?.claims24h||0);const score=Math.min(100,Math.round((criticalPriority/Math.max(unified.length,1))*1500 + Math.min(35,epssHigh/8) + Math.min(30,rw24*2)));$('pulseScore').textContent=score||'—';const label=score>=75?'HEIGHTENED':score>=50?'ELEVATED':score>=25?'GUARDED':'NORMAL';$('pulseLabel').textContent=`${label} external threat posture`;$('pulseStatus').textContent=label;$('pulseStatus').dataset.level=label.toLowerCase();$('pulseNarrative').textContent=sourceReady(RW)?`${fmt(criticalPriority)} KEVs currently rank Critical by CTI priority, while ${fmt(rw24)} ransomware claims in the latest feed were discovered within 24 hours.`:'Vulnerability intelligence is live. Ransomware activity enrichment is waiting for its first collection.';}
function renderEpss(){if(!sourceReady(EPSS)){['epssCoverage','epss10','epss99'].forEach(id=>$(id).textContent='—');return;}$('epssCoverage').textContent=`${Number(EPSS.stats.coveragePercent||0).toFixed(1)}%`;$('epssCoverageHint').textContent=`${fmt(EPSS.stats.matched)} KEVs scored`;$('epss10').textContent=fmt(EPSS.stats.epssGe10);$('epss99').textContent=fmt(EPSS.stats.percentileGe99);$('epssScoreDate').textContent=`Score date ${EPSS.meta.scoreDate||'current'}`;}
function renderSeverity(){if(!sourceReady(NVD)){return;}const s=NVD.stats;$('sevCritical').textContent=fmt(s.critical);$('sevHigh').textContent=fmt(s.high);$('sevMedium').textContent=fmt(s.medium);$('sevLow').textContent=fmt(s.low);$('severityCoverage').textContent=`${Number(s.coveragePercent||0).toFixed(1)}% CVSS coverage`;const total=Math.max(1,Number(s.total||0));$('severityStack').innerHTML=[['critical',s.critical],['high',s.high],['medium',s.medium],['low',s.low],['unknown',s.unknown]].map(([k,n])=>`<span class="stack-${k}" style="width:${Number(n||0)/total*100}%" title="${k}: ${fmt(n)}"></span>`).join('');}
function renderVendors(){const list=KEV?.stats?.topVendors||[];const max=Math.max(...list.map(x=>x.count),1);$('vendors').innerHTML=list.map(v=>`<div class="vendor-row"><div class="vendor-name"><strong>${esc(v.name)}</strong><span>${fmt(v.count)}</span></div><div class="vendor-bar"><div class="vendor-fill" style="width:${Math.max(4,v.count/max*100)}%"></div></div></div>`).join('');$('vendorCount').textContent=`${list.length} vendors shown`;}
function renderRansomware(){const ready=sourceReady(RW);['rwRecentClaims','rw24hCard','rwTrackedGroups','rwCountriesCard','rwSectors'].forEach(id=>$(id).textContent='—');if(!ready){$('rwTopGroups').innerHTML='<div class="empty-state">Run “Update Ransomware Intelligence” in GitHub Actions.</div>';$('rwCountriesList').innerHTML=$('rwSectorsList').innerHTML='';$('rwLiveFeed').innerHTML='<div class="empty-state">Waiting for first ransomware collection…</div>';return;}$('rwRecentClaims').textContent=fmt(RW.stats.recentClaims);$('rw24hCard').textContent=fmt(RW.stats.claims24h);$('rwTrackedGroups').textContent=fmt(RW.stats.trackedGroups);$('rwCountriesCard').textContent=fmt(RW.stats.countriesRecent);$('rwSectors').textContent=fmt(RW.stats.sectorsRecent);$('rwGroupSample').textContent=`${fmt(RW.stats.recentClaims)} latest claims`;renderRanking('rwTopGroups',RW.topGroups||[],8,true);renderRanking('rwCountriesList',RW.topCountries||[],7,false);renderRanking('rwSectorsList',RW.topSectors||[],7,false);renderActivity(RW.dailyActivity||[]);$('rwLiveFeed').innerHTML=(RW.victims||[]).slice(0,12).map(v=>`<div class="claim-item"><div class="claim-marker"></div><div class="claim-copy"><div><strong>${esc(v.victim||'Unknown')}</strong><span class="group-tag">${esc(v.group||'Unknown')}</span></div><small>${esc(v.country||'Unknown')} · ${esc(v.sector||'Unspecified')} · ${relTime(v.discovered)}</small></div></div>`).join('')||'<div class="empty-state">No recent claims returned.</div>';}
const ASEAN_MEMBERS=[
  {name:'Malaysia',code:'MY',flag:'🇲🇾',aliases:['MALAYSIA','MY','MYS']},
  {name:'Singapore',code:'SG',flag:'🇸🇬',aliases:['SINGAPORE','SG','SGP']},
  {name:'Indonesia',code:'ID',flag:'🇮🇩',aliases:['INDONESIA','ID','IDN']},
  {name:'Thailand',code:'TH',flag:'🇹🇭',aliases:['THAILAND','TH','THA']},
  {name:'Philippines',code:'PH',flag:'🇵🇭',aliases:['PHILIPPINES','PHILIPPINE','PH','PHL']},
  {name:'Viet Nam',code:'VN',flag:'🇻🇳',aliases:['VIET NAM','VIETNAM','VN','VNM']},
  {name:'Brunei Darussalam',code:'BN',flag:'🇧🇳',aliases:['BRUNEI','BRUNEI DARUSSALAM','BN','BRN']},
  {name:'Cambodia',code:'KH',flag:'🇰🇭',aliases:['CAMBODIA','KH','KHM']},
  {name:'Lao PDR',code:'LA',flag:'🇱🇦',aliases:['LAOS','LAO','LAO PDR','LAO PEOPLE S DEMOCRATIC REPUBLIC','LA','LAO']},
  {name:'Myanmar',code:'MM',flag:'🇲🇲',aliases:['MYANMAR','BURMA','MM','MMR']},
  {name:'Timor-Leste',code:'TL',flag:'🇹🇱',aliases:['TIMOR-LESTE','TIMOR LESTE','EAST TIMOR','TL','TLS']}
];
function cleanCountry(v){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();}
function aseanMember(raw){const x=cleanCountry(raw);if(!x)return null;return ASEAN_MEMBERS.find(m=>m.aliases.some(a=>cleanCountry(a)===x))||null;}
function withinDays(v,days){if(!v)return false;const t=new Date(v).getTime();return Number.isFinite(t)&&(Date.now()-t)<=days*86400000&&(Date.now()-t)>=-86400000;}
function countBy(items,keyFn){const m=new Map();for(const x of items){const k=keyFn(x);if(!k)continue;m.set(k,(m.get(k)||0)+1);}return [...m.entries()].map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name));}
function safeMycertUrl(v){try{const u=new URL(v,'https://mycert.org.my');return /(^|\.)mycert\.org\.my$/i.test(u.hostname)?u.href:'#';}catch{return '#';}}
function renderRegional(){
  const victims=sourceReady(RW)?(RW.victims||[]):[];
  const regional=victims.map(v=>({v,member:aseanMember(v.country)})).filter(x=>x.member);
  const aseanVictims=regional.map(x=>({...x.v,_member:x.member}));
  const malaysia=aseanVictims.filter(v=>v._member.code==='MY');
  const a24=aseanVictims.filter(v=>withinDays(v.discovered,1)).length,a7=aseanVictims.filter(v=>withinDays(v.discovered,7)).length;
  const my24=malaysia.filter(v=>withinDays(v.discovered,1)).length,my7=malaysia.filter(v=>withinDays(v.discovered,7)).length,my30=malaysia.filter(v=>withinDays(v.discovered,30)).length;
  const countries=countBy(aseanVictims,v=>v._member.name),groups=countBy(aseanVictims,v=>v.group||'Unknown'),sectors=countBy(aseanVictims,v=>v.sector||'Unspecified');
  const myGroups=countBy(malaysia,v=>v.group||'Unknown');
  $('aseanClaimsLoaded').textContent=sourceReady(RW)?fmt(aseanVictims.length):'—';$('aseanClaims24').textContent=sourceReady(RW)?fmt(a24):'—';$('aseanClaims7').textContent=sourceReady(RW)?fmt(a7):'—';$('aseanCountriesActive').textContent=sourceReady(RW)?fmt(countries.length):'—';$('aseanTopCountry').textContent=countries[0]?.name||'—';$('aseanShare').textContent=sourceReady(RW)&&victims.length?`${(aseanVictims.length/victims.length*100).toFixed(1)}%`:'—';
  $('myClaims24').textContent=sourceReady(RW)?fmt(my24):'—';$('myClaims7').textContent=sourceReady(RW)?fmt(my7):'—';$('myClaims30').textContent=sourceReady(RW)?fmt(my30):'—';$('myTopGroup').textContent=myGroups[0]?.name||'—';
  const criticalSignals=Number(MYCERT?.stats?.criticalSignals||0),ransomSignals=Number(MYCERT?.stats?.ransomwareSignals||0);const signal=Math.min(100,my24*18+Math.min(my7,8)*7+Math.min(my30,15)*3+Math.min(criticalSignals,6)*5+Math.min(ransomSignals,3)*8);const level=signal>=70?'HEIGHTENED':signal>=45?'ELEVATED':signal>=20?'GUARDED':'LOW';$('malaysiaSignalScore').textContent=sourceReady(RW)||sourceReady(MYCERT)?signal:'—';$('malaysiaSignalLevel').textContent=level;$('malaysiaSignalLevel').dataset.level=level.toLowerCase();
  const latest=MYCERT?.advisories?.[0];$('malaysiaNarrative').textContent=latest?`${my30} Malaysia ransomware claim${my30===1?'':'s'} appear within 30 days in the loaded feed. Latest MyCERT signal: ${latest.title}`:`${my30} Malaysia ransomware claim${my30===1?'':'s'} appear within 30 days in the loaded feed. MyCERT advisory collection is pending.`;
  const counts=new Map(countries.map(x=>[x.name,x.count]));const max=Math.max(...ASEAN_MEMBERS.map(m=>counts.get(m.name)||0),1);$('aseanCountryGrid').innerHTML=ASEAN_MEMBERS.map(m=>{const n=counts.get(m.name)||0;const pct=n/max*100;return `<div class="asean-country ${m.code==='MY'?'is-malaysia':''}"><div class="country-top"><span class="country-flag">${m.flag}</span><div><strong>${esc(m.name)}</strong><small>${m.code}</small></div><b>${fmt(n)}</b></div><div class="country-meter"><i style="width:${n?Math.max(5,pct):0}%"></i></div><small>${n?'claims in loaded feed':'no claim in loaded feed'}</small></div>`;}).join('');$('aseanMatrixHint').textContent=`${fmt(aseanVictims.length)} regional claims · ${fmt(countries.length)} countries active`;
  $('aseanGroupCount').textContent=`${fmt(groups.length)} groups`;renderRanking('aseanTopGroups',groups,8,true);renderRanking('aseanTopSectors',sectors,8,false);
  renderMycert();
}
function renderMycert(){const ready=sourceReady(MYCERT),feed=$('mycertFeed');if(!ready){$('mycertStatusText').textContent='Run “Update MyCERT Intelligence” in GitHub Actions';feed.innerHTML='<div class="empty-state">Waiting for first MyCERT collection…</div>';return;}const degraded=MYCERT?.meta?.lastAttemptStatus==='failed';$('mycertStatusText').textContent=degraded?'Latest saved data · current refresh degraded':`${fmt(MYCERT.stats?.totalLoaded)} advisories loaded`;
  feed.innerHTML=(MYCERT.advisories||[]).slice(0,10).map(a=>{const u=safeMycertUrl(a.url);return `<a class="mycert-item" href="${esc(u)}" ${u==='#'?'':'target="_blank" rel="noopener"'}><div class="mycert-date"><strong>${esc(a.date||'—')}</strong><span>${esc(a.id||'MYCERT')}</span></div><div class="mycert-copy"><div><span class="mycert-type type-${String(a.type||'advisory').toLowerCase()}">${esc(a.type||'Advisory')}</span>${a.severity?`<span class="mycert-severity">${esc(a.severity)}</span>`:''}</div><strong>${esc(a.title||'MyCERT advisory')}</strong>${a.cves?.length?`<small>${a.cves.map(esc).join(' · ')}</small>`:''}</div><span class="mycert-arrow">↗</span></a>`;}).join('')||'<div class="empty-state">No advisories parsed from MyCERT.</div>';
}

function renderRanking(id,list,limit,numbered){const max=Math.max(...list.map(x=>x.count),1);$(id).innerHTML=list.slice(0,limit).map((x,i)=>`<div class="rank-row">${numbered?`<span class="rank-num">${String(i+1).padStart(2,'0')}</span>`:''}<div class="rank-main"><div><strong>${esc(x.name)}</strong><span>${fmt(x.count)}</span></div><div class="rank-bar"><i style="width:${Math.max(5,x.count/max*100)}%"></i></div></div></div>`).join('')||'<div class="empty-state">No activity data.</div>';}
function renderActivity(data){if(!data.length){$('activityChart').innerHTML='<div class="empty-state">No dated claims in the latest feed.</div>';return;}const w=820,h=230,p=28,max=Math.max(...data.map(x=>x.count),1);const pts=data.map((d,i)=>{const x=p+(i*(w-2*p)/Math.max(data.length-1,1));const y=h-p-(d.count/max)*(h-2*p);return{x,y,d};});const poly=pts.map(p=>`${p.x},${p.y}`).join(' ');const bars=pts.map((p,i)=>{const bw=Math.max(8,(w-2*p)/(data.length*1.8));return`<rect x="${p.x-bw/2}" y="${p.y}" width="${bw}" height="${h-p-p.y}" rx="4" class="chart-bar"/><circle cx="${p.x}" cy="${p.y}" r="4" class="chart-dot"/>`;}).join('');const labels=pts.map((p,i)=>i%Math.ceil(data.length/6)===0||i===data.length-1?`<text x="${p.x}" y="${h-5}" text-anchor="middle">${p.d.date.slice(5)}</text>`:'').join('');$('activityChart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Recent ransomware claims activity"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#56e6ff" stop-opacity=".28"/><stop offset="1" stop-color="#56e6ff" stop-opacity="0"/></linearGradient></defs><polyline points="${poly}" class="chart-line"/>${bars}${labels}</svg>`;const first=data[0]?.count||0,last=data[data.length-1]?.count||0;$('rwTrendLabel').textContent=last>first?'RISING':last<first?'EASING':'STEADY';}
function epssMatch(x,f){const p=x.epss?.epss;if(f==='all')return true;if(p==null)return false;return f==='50'?p>=.5:f==='10'?p>=.1:f==='1'?p>=.01:f==='lt1'?p<.01:true;}
function getFiltered(){const q=$('search').value.trim().toLowerCase(),sev=$('severityFilter').value,ep=$('epssFilter').value,pri=$('priorityFilter').value,ran=$('ransomFilter').value;return buildUnified().filter(v=>{const s=String(v.nvd?.cvss?.severity||'UNKNOWN').toUpperCase();const hay=`${v.id} ${v.vendor} ${v.product} ${v.vulnerabilityName} ${v.nvd?.description||''}`.toLowerCase();return(!q||hay.includes(q))&&(sev==='all'||s===sev)&&epssMatch(v,ep)&&(pri==='all'||v.priority.label===pri)&&(ran==='all'||(ran==='yes'?v.ransomware:!v.ransomware));});}
function renderTable(){const items=getFiltered();const pages=Math.max(1,Math.ceil(items.length/PAGE_SIZE));PAGE=Math.min(PAGE,pages);const slice=items.slice((PAGE-1)*PAGE_SIZE,PAGE*PAGE_SIZE);$('resultLabel').textContent=`${fmt(items.length)} matching records · 50 per page`;$('pageLabel').textContent=`Page ${PAGE} of ${pages}`;$('prevPage').disabled=PAGE<=1;$('nextPage').disabled=PAGE>=pages;$('rows').innerHTML=slice.map(v=>{const cv=v.nvd?.cvss||{},score=cv.score==null?'—':Number(cv.score).toFixed(1),sev=String(cv.severity||'UNKNOWN').toUpperCase(),ep=v.epss?`${(Number(v.epss.epss)*100).toFixed(2)}%`:'—';return`<tr><td><strong class="cve">${esc(v.id)}</strong><small>${esc(v.dateAdded||'')}</small></td><td><strong>${esc(v.vendor)}</strong><small>${esc(v.product)}</small></td><td><b class="cvss">${score}</b><span class="sev-badge sev-${sev.toLowerCase()}">${esc(sev)}</span></td><td><strong class="epss">${ep}</strong><small>${v.epss?`${(Number(v.epss.percentile)*100).toFixed(1)} percentile`:''}</small></td><td><span class="pill ${v.ransomware?'pill-red':'pill-green'}">${v.ransomware?'KNOWN':'NOT KNOWN'}</span></td><td><span class="priority p-${v.priority.label.toLowerCase()}">${v.priority.label}</span><small>${v.priority.score}/100</small></td><td class="intel-cell"><strong>${esc(v.vulnerabilityName)}</strong><small>${esc(v.nvd?.description||v.description||'')}</small></td><td class="action-cell">${esc(v.requiredAction||'—')}</td></tr>`;}).join('')||'<tr><td colspan="8" class="empty-state">No records match your filters.</td></tr>';}
async function fetchJson(path){const r=await fetch(`${path}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${path}: HTTP ${r.status}`);return r.json();}
async function load(){const res=await Promise.allSettled(['data/kev.json','data/nvd.json','data/epss.json','data/ransomware.json','data/mycert.json'].map(fetchJson));[KEV,NVD,EPSS,RW,MYCERT]=res.map(x=>x.status==='fulfilled'?x.value:null);NVD_BY_ID=sourceReady(NVD)?new Map((NVD.vulnerabilities||[]).map(v=>[v.id,v])):new Map();EPSS_BY_ID=sourceReady(EPSS)?new Map((EPSS.vulnerabilities||[]).map(v=>[v.id,v])):new Map();renderHeader();renderTopMetrics();renderEpss();renderSeverity();renderVendors();renderRansomware();renderRegional();renderTable();}
['search','severityFilter','epssFilter','priorityFilter','ransomFilter'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',()=>{PAGE=1;renderTable();}));$('prevPage').addEventListener('click',()=>{if(PAGE>1){PAGE--;renderTable();document.querySelector('.intelligence-table-card').scrollIntoView({behavior:'smooth',block:'start'});}});$('nextPage').addEventListener('click',()=>{PAGE++;renderTable();document.querySelector('.intelligence-table-card').scrollIntoView({behavior:'smooth',block:'start'});});
load();setInterval(load,5*60*1000);
